# Generated by Django 5.1.1 on 2024-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Example_slug', unique=True),
            preserve_default=False,
        ),
    ]
